# vim: sw=2 ai ts=104
---
############
# Customize these via the all/customize.yml file
############

ansible_user: root

hostname: "{{ inventory_hostname }}.{{ domain_name }}"

router_server: "{{ groups.routers | default([]) | first | default(none) }}"
router_server_ip: "{{ 'localhost' if not router_server else hostvars[router_server].nic.ip | ipaddr('address')}}"

# default memory for all VMs
# vm_memory: 2GiB
# default template for all VMs
# vm_template: "{{ vm_rhel_template }}"
