---
# vim: sw=2 ts=102 ai

- include: satellite_helper_callsatellite.yml
  vars:
    call_name: lifecycle environments
    call_api: "/katello/api/organizations/{{ org_id }}/environments"

- name: Checking environments
  set_fact:
    tmp: dummy
  register: environment_check
  changed_when: |
    item.name not in call_output.json.results | map(attribute='name') | list
  with_items: "{{ satellite_hammer_environments }}"
  loop_control:
    label: "{{ item.name }}"

- name: Creating environments
  command: "/usr/bin/hammer --output json lifecycle-environment create --name '{{item.item.name}}' --description '{{item.item.description}}' --prior '{{item.item.prior}}' {{ ORG_ID }}"
  when: item.changed
  with_items: "{{ environment_check.results }}"
  loop_control:
    label: "{{ item.item.name }}"
