---
# vim: sw=2 ts=2 ai expandtab
- name: "Provisioning|Cleanup | Get list of all templates belonging to Org: {{ satellite_default_organization }}"
  command: "/usr/bin/hammer --output=json template list --organization='{{ satellite_default_organization }}'"
  register: org_templates
  changed_when: false

- name: "Provisioning|Cleanup | Get list of all templates belonging to Loc: {{ satellite_default_location }}"
  command: "/usr/bin/hammer --output=json template list --location='{{ satellite_default_location }}'"
  register: loc_templates
  changed_when: false

- name: "Provisioning|Cleanup | Merging lists to dict"
  set_fact:
    template_map: "{{ dict( (org_list + loc_list) | json_query('[*][Id, Name]')) }}"
  vars:
    org_list: "{{ org_templates.stdout | from_json | list }}"
    loc_list: "{{ loc_templates.stdout | from_json | list }}"

- name: "Provisioning|Cleanup | Filtering for items that aren't in the ok_template_list"
  set_fact:
    template_map: "{{ [ item.key, item.value ] }}"
  when: item.value not in ok_template_list
  with_dict: "{{ template_map }}"
  register: tmp

- name: "Provisioning|Cleanup | coerce template_map of results of array of arrays into dict"
  set_fact:
    template_map: "{{ dict( tmp.results | map(attribute='ansible_facts') | select('defined') | map(attribute='template_map') | list) }}"

- name: "Provisioning|Cleanup | Easy Way: Trying to remove location and organization directly"
  command: "/usr/bin/hammer template update --id {{ item.key }} --location-ids= --organization-ids="
  register: remove_direct
  changed_when: remove_direct.rc != 0
  failed_when: remove_direct.rc not in [0, 65]
  with_dict: "{{ template_map }}"

- name: "Provisioning|Cleanup | Hard Way: Disassociating location from template"
  command: "/usr/bin/hammer location remove-config-template --config-template-id {{ item.item.key }} --name '{{ satellite_default_location }}'"
  when: remove_direct.changed and item.changed
  with_items: "{{ remove_direct.results }}"
  loop_control:
    label: "{{ item.item.key }} => {{ item.item.value }}"
- name: "Provisioning|Cleanup | Hard Way: Disassociating organization from template"
  command: "/usr/bin/hammer organization remove-config-template --config-template-id {{ item.item.key }} --name '{{ satellite_default_organization }}'"
  when: remove_direct.changed and item.changed
  with_items: "{{ remove_direct.results }}"
  loop_control:
    label: "{{ item.item.key }} => {{ item.item.value }}"
