# vim: sw=2 ai ts=10240
---
- name: Unconfigure Demo VMs
  hosts: demo-vms
  vars:
    vms_clean: true
  gather_facts: False
  roles: [rhel]
  tasks:
    - meta: clear_host_errors
    - meta: refresh_inventory
  tags: [rhel]

- name: Remove all VMs
  hosts: demo-vms
  gather_facts: false
  connection: local
  vars:
    vms_clean: true
  roles: [vms-ovirt]
  tags: [ovirt]

- name: Remove ssh keys
  hosts: demo-vms
  gather_facts: false
  connection: local
  serial: 1
  tasks: 
    - name: assign_facts - ip address
      set_fact:
        ip: "{{ ii[2] | ipaddr('address') }}"
      with_items: "{{ (ip | default('')).split(',') | first}}"
      when: item and ii
      vars:
        ii: "{{ item.split(':') }}"

    - name: "Removing ssh key for host {{ inventory_hostname }} -> {{ ip }}"
      command: "{{ item }}"
      with_items: "{{ cmds }}"
      vars:
        cmds:
          - /usr/bin/ssh-keygen -R "{{ inventory_hostname }}"
          - /usr/bin/ssh-keygen -R "{{ inventory_hostname }}.{{ domain_name }}"
          - /usr/bin/ssh-keygen -R "{{ ansible_host }}"

  tags: [sshkey]
