# vim: ts=2 sw=2 expandtab ai
---
- name: Configure satellite capsules
  any_errors_fatal: true
  force_handlers: true
  hosts: capsules
  gather_facts: true
  connection: smart
  vars:
    satellite_subscription_ak: RHEL7-CAPSULE
    satellite_subscription_hg: RHEL7-Server
    subscription_ak: ignore
    subscription_register: false
    satellite_skip_puppet: true
    satellite_client_repos: "{{ satellite_capsule_repos }}"
  roles:
    - satellite-capsule
