# vim: ts=2 sw=2 ai expandtab
---

- name: ensure swap is on masters
  hosts: ipaservers
  gather_facts: true
  connection: smart
  vars:
    docker_ovirt_agent: registry.access.redhat.com/rhev4/rhevm-guest-agent:latest

  tasks:

  - name: create swap
    command: /usr/sbin/mkswap /dev/vdb
    when: not ansible_swaptotal_mb

  - name: Write swap entry in fstab
    mount: name=none
      src=/dev/vdb
      fstype=swap
      opts=sw
      passno=0
      dump=0
      state=present
    when: not ansible_swaptotal_mb

  - name: enable swap
    command: /usr/sbin/swapon /dev/vdb
    when: not ansible_swaptotal_mb

  - name: install psmisc,vim,screen
    yum:
      name: psmisc,vim,screen
      state: latest
    when: ansible_pkg_mgr == 'yum'

  - name: install ipa-server
    yum:
      name: ipa-server
      state: installed
    when: ansible_pkg_mgr == 'yum'

  - name: disable chronyd
    systemd:
      name: chronyd
      state: stopped
      enabled: no

  - name: enable ntpd
    systemd:
      name: ntpd
      state: started
      enabled: yes
      
  - name: "Start ovirt-guest-agent container: {{ docker_ovirt_agent }}"
    docker_container:
      image: "{{ docker_ovirt_agent }}"
      name: ovirt_guest_agent
      pid_mode: host
      network_mode: host
      privileged: true
      state: started
      restart_policy: always
      env:
        HOST: /host
        container: docker
        IMAGE: "{{ docker_ovirt_agent }}"
        NAME: ovirt_guest_agent
      volumes:
        - /:/host
        - /proc:/hostproc
        - /dev/virtio-ports/com.redhat.rhevm.vdsm:/dev/virtio-ports/com.redhat.rhevm.vdsm
    when: docker_ovirt_agent is not none and ansible_pkg_mgr != 'yum'
