# vim: sw=2 ai ts=10240
---
- name: Create Snapshot
  hosts: ovirt-hosts
  gather_facts: false
  connection: smart
  roles:
    - base-facts
  vars:
    ovirt_insecure: true

  tasks:
    - name: "Set vm_name if not defined"
      set_fact:
        vm_name: "{{ vm_name | default(inventory_hostname) }}"

    - name: expand vm_snapshot_name
      set_fact:
        vm_description: "{{ vm_snapshot_name | replace('_', ' ') }}"

    - name: synchoronize filesystem before snapshot
      command: /usr/bin/sync
      ignore_errors: true

    - meta: clear_host_errors

    - name: Login to oVirt manager
      connection: local
      ovirt_auth:
        url: "{{ ovirt_url }}"
        username: "{{ ovirt_user }}"
        password: "{{ ovirt_pass }}"
        insecure: "{{ ovirt_insecure }}"
      when: ovirt_auth is not defined
      run_once: True

    - name: "search snapshot ({{ vm_description }})"
      connection: local
      ovirt_snapshots_facts:
        auth: "{{ ovirt_auth }}"
        vm: "{{ vm_name }}"
        description: "{{ vm_description }}"
      
    - name: "create snapshot ({{ vm_description }})"
      connection: local
      ovirt_snapshots:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ vm_name }}"
        description: "{{ vm_description }}"
        use_memory: false
        wait: true
      when: (ovirt_snapshots is defined) and (ovirt_snapshots | length) < 1
